### PR TITLE
Writes specs as requested

### PR DESCRIPTION
**Pull request by acolchagoff**

### CODE REVIEW

**Comment by acolchagoff** [comment]
@barthez  I wrote some specs, as well as came up with an additional fix for that bug (it turns out the images were included but in a different way...)

**Comment by acolchagoff** [comment]
also my specs turned up a bug in my code that I fixed. Since it looks like you did a release I bumped the version number as well.

**Comment by barthez** [comment]
Oh, thanks. I will try to release it over the weekend.

**Comment by barthez** [comment]
Thank you @denodster. v0.0.5 released.

**Pull request merged**
